"""INITIAL

Revision ID: 21026e4d773b
Revises: 
Create Date: 2025-01-19 21:44:08.910533

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '21026e4d773b'
down_revision = None
branch_labels = None
depends_on = None


_ENUMS=[]


def upgrade() -> None:
    for _ENUM in _ENUMS:
        _ENUM.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.Enum('YOUTUBE_MUSIC', 'SPOTIFY', name='servicetype_enum'), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credentials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('credentials')
    op.drop_table('applications')
    # ### end Alembic commands ###
    for _ENUM in _ENUMS:
        _ENUM.drop(op.get_bind(), checkfirst=True)
