"""APP_NAME

Revision ID: 7878604896e0
Revises: 21026e4d773b
Create Date: 2025-12-21 17:55:49.140597

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '7878604896e0'
down_revision = '21026e4d773b'
branch_labels = None
depends_on = None


_ENUMS=[]


def upgrade() -> None:
    for _ENUM in _ENUMS:
        _ENUM.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'name')
    # ### end Alembic commands ###
    for _ENUM in _ENUMS:
        _ENUM.drop(op.get_bind(), checkfirst=True)
