"""USER_INFO

Revision ID: 9dcf7108cb87
Revises: 7878604896e0
Create Date: 2025-12-21 20:07:30.755942

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '9dcf7108cb87'
down_revision = '7878604896e0'
branch_labels = None
depends_on = None


_ENUMS=[]


def upgrade() -> None:
    for _ENUM in _ENUMS:
        _ENUM.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credentials', sa.Column('username', sa.String(), nullable=False, server_default=""))
    op.add_column('credentials', sa.Column('avatar', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credentials', 'avatar')
    op.drop_column('credentials', 'username')
    # ### end Alembic commands ###
    for _ENUM in _ENUMS:
        _ENUM.drop(op.get_bind(), checkfirst=True)
